### ISSUE TITLE
dragSprite() not working on headless

### ISSUE THREAD

**Issue by martingallardo23** [se2p/whisker#11]
Hi! I found a problem where using `t.dragSprite()` works when using whisker loaded on chrome but fails when running the tests on headless mode. Is this a known issue and, if so, is there any way to work around this?

This is the code I'm using:

```javascript
const test = async function (t) {
    let sprite = t.getSprite('Basketball');
    t.dragSprite('Basketball', 0, 0);
    t.assert.ok(sprite.x == 0 && sprite.y == 0, "didn't move to 0 0")
    t.end()
}
```

Thanks!

**Comment by FeldiPat** [comment]
Hi! I might have found the issue and pushed a fix for it. Could you please test if the bug still occurs? If so, please also share your .sb3 file so I can reproduce the bug on my machine. 

Thanks for reporting!

**Comment by martingallardo23** [comment]
It worked perfectly! Thanks so much!

**Comment by FeldiPat** [comment]
Nice, I'll close the issue then 🙂
